arrowParens: avoid
# editorconfig: true
insertPragma: false
bracketSpacing: false
semi: false
useTabs: true
singleQuote: true
trailingComma: all
printWidth: 1000
overrides:
  - files: '*.svelte'
    options:
      parser: svelte
      plugins:
        - prettier-plugin-svelte
